spring:
  kafka:
    bootstrap-servers: 127.0.0.1:19092,127.0.0.1:29092,127.0.0.1:39092
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 5
      properties:
        acks: 1
        retries: 10
        retry.backoff.ms: 100
  threads:
    virtual:
      enabled: true

app:
  kafka:
    topic:
      generic: demo-kafka-generic
      person: demo-kafka-persons
      donation: dmeo-kafka-donations
