services:
  kafka-node1:
    container_name: kafka-node1
    image: demo-kraft-kafka:latest
    ports:
      - "19092:19092"
    networks:
      - kafka-net
    volumes:
      - ./config/kafka-node1/server.properties:/opt/kafka/config/kraft/server.properties
  kafka-node2:
    container_name: kafka-node2
    image: demo-kraft-kafka:latest
    ports:
      - "29092:29092"
    networks:
      - kafka-net
    volumes:
      - ./config/kafka-node2/server.properties:/opt/kafka/config/kraft/server.properties
  kafka-node3:
    container_name: kafka-node3
    image: demo-kraft-kafka:latest
    ports:
      - "39092:39092"
    networks:
      - kafka-net
    volumes:
      - ./config/kafka-node3/server.properties:/opt/kafka/config/kraft/server.properties
networks:
  kafka-net:
    driver: bridge
