spring:
  kafka:
    bootstrap-servers: 127.0.0.1:19092,127.0.0.1:29092,127.0.0.1:39092
    consumer:
      auto-offset-reset: earliest
      group-id: demo-kafka-group
  threads:
    virtual:
      enabled: true
app:
  kafka:
    topics:
      generic: demo-kafka-generic
      person: demo-kafka-persons
      person-forward: demo-kafka-persons-forward
      donation: demo-kafka-donations
      donation-dlt: demo-kafka-donations.dlt
      donation-retry: demo-kafka-donations.retry
